// DRAWDOWN OS — MARKETPLACE CONNECTOR REGISTRY
// SEED MANIFEST DEFINITIONS & CAPABILITY MATRIX FOR 17 PRIORITY CHANNELS

import { 
  ConnectorManifest, 
  ConnectorCapabilities, 
  CapabilityStatus,
  ConnectorTelemetryMetrics 
} from './types';

// Utility for default capability set
function defaultCapabilities(overrides: Partial<ConnectorCapabilities> = {}): ConnectorCapabilities {
  return {
    canCreateProduct: 'RESEARCH_REQUIRED',
    canReadProduct: 'RESEARCH_REQUIRED',
    canUpdateProduct: 'RESEARCH_REQUIRED',
    canDeleteProduct: 'UNSUPPORTED',
    canArchiveProduct: 'UNSUPPORTED',
    canPauseProduct: 'RESEARCH_REQUIRED',
    canCreateListing: 'RESEARCH_REQUIRED',
    canReadListing: 'RESEARCH_REQUIRED',
    canUpdateListing: 'RESEARCH_REQUIRED',
    canPauseListing: 'RESEARCH_REQUIRED',
    canDeleteListing: 'UNSUPPORTED',
    canVerifyListing: 'RESEARCH_REQUIRED',
    canUploadFiles: 'RESEARCH_REQUIRED',
    canReplaceFiles: 'RESEARCH_REQUIRED',
    supportsPDF: 'SUPPORTED',
    supportsEPUB: 'RESEARCH_REQUIRED',
    supportsAudio: 'UNSUPPORTED',
    supportsZIP: 'SUPPORTED',
    canSetPrice: 'RESEARCH_REQUIRED',
    canUpdatePrice: 'RESEARCH_REQUIRED',
    supportsTerritorialPricing: 'RESEARCH_REQUIRED',
    supportsMultipleCurrencies: 'SUPPORTED',
    supportsSalesPricing: 'RESEARCH_REQUIRED',
    canReadOrders: 'RESEARCH_REQUIRED',
    canReadTransactions: 'RESEARCH_REQUIRED',
    canReadFees: 'RESEARCH_REQUIRED',
    canReadRefunds: 'RESEARCH_REQUIRED',
    canReadPayouts: 'RESEARCH_REQUIRED',
    canReadRoyalties: 'RESEARCH_REQUIRED',
    canReadCustomer: 'RESEARCH_REQUIRED',
    customerDataRestricted: 'SUPPORTED',
    hasAffiliateProgram: 'RESEARCH_REQUIRED',
    canReadAffiliates: 'RESEARCH_REQUIRED',
    supportsWebhooks: 'RESEARCH_REQUIRED',
    supportsIdempotency: 'RESEARCH_REQUIRED',
    supportsSafeRetry: 'SUPPORTED',
    supportsRollback: 'PARTIAL',
    supportsSandbox: 'RESEARCH_REQUIRED',
    ...overrides,
  };
}

export const CONNECTOR_MANIFESTS_REGISTRY: Record<string, ConnectorManifest> = {
  'ch-whop': {
    id: 'ch-whop',
    name: 'Whop Direct API',
    category: 'DIRECT_API',
    officialWebsite: 'https://whop.com',
    officialDocsUrl: 'https://dev.whop.com',
    authType: 'API_KEY',
    versionInfo: {
      connectorVersion: '1.2.0',
      apiVersion: 'v2',
      manifestVersion: '1.0.0',
      certificationVersion: '2026.1',
      lastVerifiedAt: '2026-08-12',
    },
    capabilities: defaultCapabilities({
      canCreateProduct: 'SUPPORTED',
      canReadProduct: 'SUPPORTED',
      canUpdateProduct: 'SUPPORTED',
      canCreateListing: 'SUPPORTED',
      canReadListing: 'SUPPORTED',
      canUpdateListing: 'SUPPORTED',
      canUploadFiles: 'SUPPORTED',
      canSetPrice: 'SUPPORTED',
      canUpdatePrice: 'SUPPORTED',
      canReadOrders: 'SUPPORTED',
      canReadTransactions: 'SUPPORTED',
      canReadFees: 'SUPPORTED',
      canReadRefunds: 'SUPPORTED',
      canReadPayouts: 'SUPPORTED',
      canReadCustomer: 'SUPPORTED',
      hasAffiliateProgram: 'SUPPORTED',
      supportsWebhooks: 'SUPPORTED',
      supportsIdempotency: 'SUPPORTED',
      supportsSandbox: 'SUPPORTED',
    }),
    capabilityEvidence: {
      'canCreateListing': {
        capability: 'canCreateListing',
        status: 'SUPPORTED',
        source: 'Official Whop v2 API Documentation',
        documentationUrl: 'https://dev.whop.com/api-reference/products/create',
        confidenceScore: 100,
      },
    },
    resources: ['Product', 'Listing', 'File', 'Price', 'Order', 'Transaction', 'Customer', 'Webhook'],
    fieldMappings: [
      { drawdownField: 'canonical.title', targetField: 'name', transformRule: 'DIRECT', isRequired: true, sampleValue: 'HOW TO TRADE' },
      { drawdownField: 'canonical.long_description', targetField: 'description', transformRule: 'STRIP_HTML', isRequired: true },
      { drawdownField: 'territorial_price.USD', targetField: 'initial_price', transformRule: 'CURRENCY_CONVERT', isRequired: true, sampleValue: '99.00' },
    ],
    actionCertifications: {
      'READ_LISTINGS': { actionType: 'READ_LISTINGS', certLevel: 'AUTOPILOT_CERTIFIED', autopilotEligible: true },
      'CREATE_LISTING': { actionType: 'CREATE_LISTING', certLevel: 'AUTOPILOT_CERTIFIED', autopilotEligible: true },
      'UPDATE_PRICE': { actionType: 'UPDATE_PRICE', certLevel: 'AUTOPILOT_CERTIFIED', autopilotEligible: true },
    },
    rateLimits: { requestsPerSecond: 10, requestsPerMinute: 600, burstLimit: 20 },
  },

  'ch-etsy': {
    id: 'ch-etsy',
    name: 'Etsy v3 Open API',
    category: 'OAUTH_API',
    officialWebsite: 'https://etsy.com',
    officialDocsUrl: 'https://developers.etsy.com',
    authType: 'OAUTH_2',
    versionInfo: {
      connectorVersion: '1.1.0',
      apiVersion: 'v3',
      manifestVersion: '1.0.0',
      certificationVersion: '2026.1',
      lastVerifiedAt: '2026-08-11',
    },
    capabilities: defaultCapabilities({
      canCreateListing: 'SUPPORTED',
      canReadListing: 'SUPPORTED',
      canUpdateListing: 'SUPPORTED',
      canUploadFiles: 'SUPPORTED',
      canSetPrice: 'SUPPORTED',
      canUpdatePrice: 'SUPPORTED',
      canReadOrders: 'SUPPORTED',
      canReadTransactions: 'SUPPORTED',
      canReadFees: 'SUPPORTED',
      supportsEPUB: 'SUPPORTED',
      supportsWebhooks: 'PARTIAL',
      supportsIdempotency: 'UNSUPPORTED',
      supportsRollback: 'UNSUPPORTED',
    }),
    capabilityEvidence: {
      'canCreateListing': {
        capability: 'canCreateListing',
        status: 'SUPPORTED',
        source: 'Etsy OpenAPI v3 reference',
        documentationUrl: 'https://developers.etsy.com/documentation/reference#operation/createDraftListing',
        confidenceScore: 95,
      },
    },
    resources: ['Listing', 'File', 'Price', 'Order', 'Transaction', 'Fee'],
    fieldMappings: [
      { drawdownField: 'canonical.title', targetField: 'title', transformRule: 'TRUNCATE', isRequired: true, sampleValue: 'HOW TO TRADE PDF' },
      { drawdownField: 'canonical.long_description', targetField: 'description', transformRule: 'STRIP_HTML', isRequired: true },
      { drawdownField: 'territorial_price.GBP', targetField: 'price', transformRule: 'CURRENCY_CONVERT', isRequired: true, sampleValue: '49.00' },
    ],
    actionCertifications: {
      'READ_LISTINGS': { actionType: 'READ_LISTINGS', certLevel: 'AUTOPILOT_CERTIFIED', autopilotEligible: true },
      'CREATE_LISTING': { actionType: 'CREATE_LISTING', certLevel: 'WRITE_CERTIFIED', autopilotEligible: false },
      'UPDATE_PRICE': { actionType: 'UPDATE_PRICE', certLevel: 'AUTOPILOT_CERTIFIED', autopilotEligible: true },
    },
    rateLimits: { requestsPerSecond: 5, requestsPerMinute: 300, burstLimit: 10 },
  },

  'ch-publishdrive': {
    id: 'ch-publishdrive',
    name: 'PublishDrive Aggregator API',
    category: 'AGGREGATOR',
    officialWebsite: 'https://publishdrive.com',
    officialDocsUrl: 'https://publishdrive.com/api-docs',
    authType: 'API_KEY',
    versionInfo: {
      connectorVersion: '2.0.0',
      apiVersion: 'v1',
      manifestVersion: '1.0.0',
      certificationVersion: '2026.1',
      lastVerifiedAt: '2026-08-10',
    },
    capabilities: defaultCapabilities({
      canCreateProduct: 'SUPPORTED',
      canReadProduct: 'SUPPORTED',
      canUploadFiles: 'SUPPORTED',
      supportsEPUB: 'SUPPORTED',
      canReadRoyalties: 'SUPPORTED',
      canReadPayouts: 'SUPPORTED',
      supportsWebhooks: 'SUPPORTED',
      supportsIdempotency: 'SUPPORTED',
    }),
    capabilityEvidence: {},
    resources: ['Product', 'File', 'RoyaltyReport', 'Payout'],
    fieldMappings: [],
    actionCertifications: {
      'ENABLE_DESTINATION': { actionType: 'ENABLE_DESTINATION', certLevel: 'AUTOPILOT_CERTIFIED', autopilotEligible: true },
    },
    rateLimits: { requestsPerSecond: 10, requestsPerMinute: 500, burstLimit: 15 },
  },

  'ch-amazon-kdp': {
    id: 'ch-amazon-kdp',
    name: 'Amazon KDP / Kindle Direct',
    category: 'HYBRID',
    officialWebsite: 'https://kdp.amazon.com',
    officialDocsUrl: 'https://kdp.amazon.com/help',
    authType: 'MANUAL',
    versionInfo: {
      connectorVersion: '1.0.0',
      apiVersion: 'N/A',
      manifestVersion: '1.0.0',
      certificationVersion: '2026.1',
      lastVerifiedAt: '2026-08-11',
    },
    capabilities: defaultCapabilities({
      canCreateListing: 'PARTIAL',
      canReadListing: 'SUPPORTED',
      canUpdatePrice: 'PARTIAL',
      canReadRoyalties: 'SUPPORTED',
      supportsEPUB: 'SUPPORTED',
    }),
    capabilityEvidence: {},
    resources: ['Listing', 'Price', 'RoyaltyReport'],
    fieldMappings: [],
    actionCertifications: {
      'READ_SALES': { actionType: 'READ_SALES', certLevel: 'READ_CERTIFIED', autopilotEligible: true },
      'CREATE_LISTING': { actionType: 'CREATE_LISTING', certLevel: 'CONFIGURED', autopilotEligible: false },
    },
    rateLimits: { requestsPerSecond: 2, requestsPerMinute: 60, burstLimit: 5 },
  },
};

export const CONNECTOR_TELEMETRY_DATA: ConnectorTelemetryMetrics[] = [
  {
    connectorId: 'ch-whop',
    name: 'Whop Direct API',
    healthScore: 100,
    healthStatus: 'HEALTHY',
    apiLatencyMs: 140,
    successRatePct: 99.8,
    lastSyncAt: '18:41',
    lastSaleAt: '18:32',
    webhookHealthPct: 100,
    rateLimitUsedPct: 12.5,
    circuitBreakerState: 'CLOSED',
    autopilotState: 'CERTIFIED',
  },
  {
    connectorId: 'ch-publishdrive',
    name: 'PublishDrive Aggregator',
    healthScore: 96,
    healthStatus: 'HEALTHY',
    apiLatencyMs: 220,
    successRatePct: 99.4,
    lastSyncAt: '18:30',
    lastSaleAt: '18:22',
    webhookHealthPct: 98.5,
    rateLimitUsedPct: 18.0,
    circuitBreakerState: 'CLOSED',
    autopilotState: 'CERTIFIED',
  },
  {
    connectorId: 'ch-etsy',
    name: 'Etsy v3 Open API',
    healthScore: 88,
    healthStatus: 'HEALTHY',
    apiLatencyMs: 340,
    successRatePct: 98.2,
    lastSyncAt: '18:38',
    lastSaleAt: '17:45',
    webhookHealthPct: 95.0,
    rateLimitUsedPct: 24.0,
    circuitBreakerState: 'CLOSED',
    autopilotState: 'PARTIAL',
  },
  {
    connectorId: 'ch-clickbank',
    name: 'ClickBank Marketplace',
    healthScore: 35,
    healthStatus: 'AUTH_FAILURE',
    apiLatencyMs: 980,
    successRatePct: 45.0,
    lastSyncAt: '18:30',
    lastSaleAt: '2026-08-01',
    webhookHealthPct: 0,
    rateLimitUsedPct: 0,
    circuitBreakerState: 'OPEN',
    autopilotState: 'BLOCKED',
  },
];
