/**
 * DRAWDOWN OS — GLOBAL LOCALISATION ENGINE
 * Demo Data — Test Product: HOW TO TRADE (DD-HTT-001)
 * Canonical Source: DD-HTT-001-EN-GB-v1.2
 */

import type {
  Territory, Locale, LocalisedEdition, TranslationUnit,
  TranslationMemoryEntry, TermBaseEntry, LocalisationOpportunity,
  LocalComplianceRule, LocalPriceRecord
} from './types';

// ─── TERRITORIES ─────────────────────────────────────────────────────────────

export const TERRITORIES: Territory[] = [
  { id: 'GB', name: 'United Kingdom', defaultCurrencyCode: 'GBP', primaryLanguages: ['en'], dateFormat: 'DD/MM/YYYY', numberFormat: '1,234.56', regulatoryContext: 'FCA Regulated Environment' },
  { id: 'US', name: 'United States', defaultCurrencyCode: 'USD', primaryLanguages: ['en', 'es'], dateFormat: 'MM/DD/YYYY', numberFormat: '1,234.56', regulatoryContext: 'SEC / NFA Regulated Environment' },
  { id: 'DE', name: 'Germany (DACH)', defaultCurrencyCode: 'EUR', primaryLanguages: ['de'], dateFormat: 'DD.MM.YYYY', numberFormat: '1.234,56', regulatoryContext: 'BaFin Regulated Environment' },
  { id: 'ES', name: 'Spain', defaultCurrencyCode: 'EUR', primaryLanguages: ['es'], dateFormat: 'DD/MM/YYYY', numberFormat: '1.234,56', regulatoryContext: 'CNMV Regulated Environment' },
  { id: 'BR', name: 'Brazil (LatAm)', defaultCurrencyCode: 'BRL', primaryLanguages: ['pt'], dateFormat: 'DD/MM/YYYY', numberFormat: '1.234,56', regulatoryContext: 'CVM Regulated Environment' },
  { id: 'FR', name: 'France', defaultCurrencyCode: 'EUR', primaryLanguages: ['fr'], dateFormat: 'DD/MM/YYYY', numberFormat: '1 234,56', regulatoryContext: 'AMF Regulated Environment' },
];

// ─── LOCALES ─────────────────────────────────────────────────────────────────

export const LOCALES: Locale[] = [
  { id: 'en-GB', languageCode: 'en', territoryCode: 'GB', localeName: 'English (United Kingdom)', textDirection: 'ltr', isActive: true },
  { id: 'en-US', languageCode: 'en', territoryCode: 'US', localeName: 'English (United States)', textDirection: 'ltr', isActive: true },
  { id: 'de-DE', languageCode: 'de', territoryCode: 'DE', localeName: 'German (Germany / DACH)', textDirection: 'ltr', isActive: true },
  { id: 'es-ES', languageCode: 'es', territoryCode: 'ES', localeName: 'Spanish (Spain)', textDirection: 'ltr', isActive: true },
  { id: 'pt-BR', languageCode: 'pt', territoryCode: 'BR', localeName: 'Portuguese (Brazil)', textDirection: 'ltr', isActive: true },
  { id: 'fr-FR', languageCode: 'fr', territoryCode: 'FR', localeName: 'French (France)', textDirection: 'ltr', isActive: true },
];

// ─── LOCALISED EDITIONS ───────────────────────────────────────────────────────

export const LOCALISED_EDITIONS: LocalisedEdition[] = [
  {
    id: 'ed-htt-en-us',
    publicationId: 'pub-dd-htt-001',
    productId: 'prod-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    sourceEditionId: 'DD-HTT-001-EN-GB-v1.2',
    sourceVersion: 'v1.2',
    languageCode: 'en',
    territoryCode: 'US',
    localeCode: 'en-US',
    localeName: 'English (United States)',
    editionVersion: 'v1.2',
    titleLocalised: 'How to Trade: The Complete Master Manual',
    subtitleLocalised: 'Institutional Risk Control, Position Sizing and Execution',
    translationMethod: 'HUMAN',
    state: 'LIVE',
    editorialStatus: 'APPROVED',
    complianceStatus: 'PASS',
    qaStatus: 'APPROVED',
    commercialStatus: 'LIVE',
    translatorName: 'Pete Currey (Editorial)',
    reviewerName: 'US Compliance Legal',
    completionPct: 100,
    totalUnits: 142,
    translatedUnits: 142,
    approvedUnits: 142,
    blockingIssuesCount: 0,
    approvedAt: '2024-04-15T00:00:00Z',
    publishedAt: '2024-04-20T00:00:00Z',
    createdAt: '2024-04-01T00:00:00Z',
    updatedAt: '2024-08-12T10:00:00Z',
  },
  {
    id: 'ed-htt-de-de',
    publicationId: 'pub-dd-htt-001',
    productId: 'prod-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    sourceEditionId: 'DD-HTT-001-EN-GB-v1.2',
    sourceVersion: 'v1.2',
    languageCode: 'de',
    territoryCode: 'DE',
    localeCode: 'de-DE',
    localeName: 'German (Germany / DACH)',
    editionVersion: 'v1.0',
    titleLocalised: 'Handeln wie ein Profi: Das Handbuch für Risikomanagement',
    subtitleLocalised: 'Positionsgrößenbestimmung, Disziplin und Ausführung',
    translationMethod: 'HYBRID',
    state: 'TRANSLATED_DRAFT',
    editorialStatus: 'EDITORIAL_REVIEW',
    complianceStatus: 'PENDING',
    qaStatus: 'NEEDS_QA',
    commercialStatus: 'PREPARING',
    translatorName: 'DACH Financial Translation Partner',
    reviewerName: 'Dr. K. Weber (DACH Reviewer)',
    completionPct: 84,
    totalUnits: 142,
    translatedUnits: 142,
    approvedUnits: 119,
    blockingIssuesCount: 2, // 2 regulatory disclaimers pending review
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-08-12T14:00:00Z',
  },
  {
    id: 'ed-htt-es-es',
    publicationId: 'pub-dd-htt-001',
    productId: 'prod-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    sourceEditionId: 'DD-HTT-001-EN-GB-v1.2',
    sourceVersion: 'v1.2',
    languageCode: 'es',
    territoryCode: 'ES',
    localeCode: 'es-ES',
    localeName: 'Spanish (Spain)',
    editionVersion: 'v1.0',
    titleLocalised: 'Cómo Operar en los Mercados: Manual de Gestión de Riesgo',
    subtitleLocalised: 'Dimensionamiento de Posición, Disciplina y Ejecución',
    translationMethod: 'AI_ASSISTED',
    state: 'COMPLIANCE_REVIEW',
    editorialStatus: 'APPROVED',
    complianceStatus: 'WARN',
    qaStatus: 'IN_REVIEW',
    commercialStatus: 'PREPARING',
    translatorName: 'Iberian Editorial Services',
    reviewerName: 'M. Garcia (Spain Compliance)',
    completionPct: 92,
    totalUnits: 142,
    translatedUnits: 142,
    approvedUnits: 130,
    blockingIssuesCount: 1,
    createdAt: '2024-06-15T00:00:00Z',
    updatedAt: '2024-08-10T11:00:00Z',
  },
  {
    id: 'ed-htt-pt-br',
    publicationId: 'pub-dd-htt-001',
    productId: 'prod-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    sourceEditionId: 'DD-HTT-001-EN-GB-v1.2',
    sourceVersion: 'v1.2',
    languageCode: 'pt',
    territoryCode: 'BR',
    localeCode: 'pt-BR',
    localeName: 'Portuguese (Brazil)',
    editionVersion: 'v1.0',
    titleLocalised: 'Manual Completo de Trading: Gestão de Risco e Execução',
    subtitleLocalised: 'Dimensionamento de Posição e Disciplina Operacional',
    translationMethod: 'AI_DRAFT',
    state: 'PREPARING',
    editorialStatus: 'PENDING',
    complianceStatus: 'PENDING',
    qaStatus: 'NOT_STARTED',
    commercialStatus: 'OPPORTUNITY',
    completionPct: 35,
    totalUnits: 142,
    translatedUnits: 50,
    approvedUnits: 0,
    blockingIssuesCount: 0,
    createdAt: '2024-07-01T00:00:00Z',
    updatedAt: '2024-08-01T00:00:00Z',
  },
];

// ─── TRANSLATION UNITS ───────────────────────────────────────────────────────

export const DEMO_TRANSLATION_UNITS: TranslationUnit[] = [
  {
    id: 'tu-001',
    editionId: 'ed-htt-de-de',
    sourceElementId: 'ce-001',
    unitType: 'HEADING',
    sourceText: 'How to Trade: The Complete Master Manual',
    sourceVersion: 'v1.2',
    sourceContext: 'Title page & main cover title',
    translatedText: 'Handeln wie ein Profi: Das Handbuch für Risikomanagement',
    translationMethod: 'HUMAN',
    status: 'APPROVED',
    complianceSensitivity: 1,
    isComplianceSensitive: false,
    tmConfidencePct: 100,
  },
  {
    id: 'tu-002',
    editionId: 'ed-htt-de-de',
    sourceElementId: 'ce-009',
    unitType: 'PARAGRAPH',
    sourceText: 'Risk management is the foundational pillar of long-term trading survival. Never risk more than 1% to 2% of total trading capital on a single position.',
    sourceVersion: 'v1.2',
    sourceContext: 'Chapter 9 — Core Risk Rules',
    translatedText: 'Risikomanagement ist das Fundament für ein langfristiges Überleben im Trading. Riskieren Sie niemals mehr als 1% bis 2% Ihres gesamten Trading-Kapitals in einer einzelnen Position.',
    translationMethod: 'AI_ASSISTED',
    status: 'APPROVED',
    complianceSensitivity: 3,
    isComplianceSensitive: false,
    tmConfidencePct: 95,
  },
  {
    id: 'tu-003',
    editionId: 'ed-htt-de-de',
    sourceElementId: 'ce-019',
    unitType: 'DISCLAIMER',
    sourceText: 'Trading financial instruments involves significant risk of capital loss. Past performance is not indicative of future results. Drawdown OS does not provide investment advice.',
    sourceVersion: 'v1.2',
    sourceContext: 'Legal & Regulatory Disclaimer (DACH overlay required)',
    translatedText: 'Der Handel mit Finanzinstrumenten birgt ein erhebliches Risiko des Kapitalverlusts. Die Wertentwicklung der Vergangenheit ist kein Indikator für zukünftige Ergebnisse.',
    translationMethod: 'AI_DRAFT',
    status: 'FLAGGED',
    complianceSensitivity: 5,
    isComplianceSensitive: true,
    reviewerNotes: 'COMPLIANCE FLAG: German BaFin mandatory risk warning overlay must be added before approval.',
    tmConfidencePct: 70,
  },
];

// ─── TRANSLATION MEMORY ───────────────────────────────────────────────────────

export const TRANSLATION_MEMORY: TranslationMemoryEntry[] = [
  { id: 'tm-001', sourcePhrase: 'risk management', approvedTranslation: 'Risikomanagement', sourceLanguage: 'en', targetLanguage: 'de', localeCode: 'de-DE', domain: 'FINANCIAL_EDUCATION', approvedBy: 'Dr. K. Weber', timesUsed: 42, lastUsedAt: '2024-08-12T00:00:00Z' },
  { id: 'tm-002', sourcePhrase: 'position sizing', approvedTranslation: 'Positionsgrößenbestimmung', sourceLanguage: 'en', targetLanguage: 'de', localeCode: 'de-DE', domain: 'FINANCIAL_EDUCATION', approvedBy: 'Dr. K. Weber', timesUsed: 28, lastUsedAt: '2024-08-12T00:00:00Z' },
  { id: 'tm-003', sourcePhrase: 'trading capital', approvedTranslation: 'Trading-Kapital', sourceLanguage: 'en', targetLanguage: 'de', localeCode: 'de-DE', domain: 'FINANCIAL_EDUCATION', approvedBy: 'Dr. K. Weber', timesUsed: 19, lastUsedAt: '2024-08-12T00:00:00Z' },
  { id: 'tm-004', sourcePhrase: 'gestión de riesgo', approvedTranslation: 'gestión de riesgo', sourceLanguage: 'en', targetLanguage: 'es', localeCode: 'es-ES', domain: 'FINANCIAL_EDUCATION', approvedBy: 'M. Garcia', timesUsed: 35, lastUsedAt: '2024-08-10T00:00:00Z' },
];

// ─── DRAWDOWN TERM BASE ───────────────────────────────────────────────────────

export const DRAWDOWN_TERM_BASE: TermBaseEntry[] = [
  {
    id: 'tb-001',
    termEn: 'Drawdown OS',
    category: 'BRAND',
    classification: 'LOCKED',
    definition: 'Canonical brand name of the operating system.',
    translations: {
      'de-DE': { preferred: 'Drawdown OS', keepInEnglish: true },
      'es-ES': { preferred: 'Drawdown OS', keepInEnglish: true },
      'pt-BR': { preferred: 'Drawdown OS', keepInEnglish: true },
    },
  },
  {
    id: 'tb-002',
    termEn: 'position sizing',
    category: 'TECHNICAL',
    classification: 'LOCALISE',
    definition: 'Calculation of specific share or contract units based on risk parameters.',
    translations: {
      'de-DE': { preferred: 'Positionsgrößenbestimmung', alternatives: ['Positionsgröße'] },
      'es-ES': { preferred: 'dimensionamiento de posición' },
      'pt-BR': { preferred: 'dimensionamento de posição' },
    },
  },
  {
    id: 'tb-003',
    termEn: 'trading signals',
    category: 'BRAND',
    classification: 'LOCKED',
    definition: 'Prohibited commercial offering in Drawdown philosophy.',
    translations: {
      'de-DE': { preferred: 'Trading-Signale', prohibited: ['Gewinnsignale'] },
      'es-ES': { preferred: 'señales de trading' },
      'pt-BR': { preferred: 'sinais de trading' },
    },
  },
];

// ─── LOCALISATION OPPORTUNITIES ───────────────────────────────────────────────

export const LOCALISATION_OPPORTUNITIES: LocalisationOpportunity[] = [
  {
    id: 'opp-loc-de',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    languageCode: 'de',
    territoryCode: 'DE',
    localeCode: 'de-DE',
    localeName: 'German (Germany / DACH)',
    priorityScore: 88,
    rsaUnlockPts: 4.2,
    unlockedMarketplaces: ['Tolino DACH', 'Kobo DACH', 'Apple Books Germany', 'Google Play Books DE', 'Amazon.de Kindle'],
    estimatedEffort: 'HIGH',
    confidence: 'HIGH',
    existingSalesSignal: '12.4% of English edition sales originate from DACH IP addresses',
    status: 'APPROVED',
  },
  {
    id: 'opp-loc-es',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    languageCode: 'es',
    territoryCode: 'ES',
    localeCode: 'es-ES',
    localeName: 'Spanish (Spain)',
    priorityScore: 76,
    rsaUnlockPts: 3.0,
    unlockedMarketplaces: ['Amazon.es Kindle', 'Apple Books Spain', 'Google Play ES', 'Hotmart Spain'],
    estimatedEffort: 'MEDIUM',
    confidence: 'HIGH',
    existingSalesSignal: 'Strong Spanish search volume for position sizing trading guides',
    status: 'APPROVED',
  },
  {
    id: 'opp-loc-pt',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    languageCode: 'pt',
    territoryCode: 'BR',
    localeCode: 'pt-BR',
    localeName: 'Portuguese (Brazil)',
    priorityScore: 72,
    rsaUnlockPts: 2.8,
    unlockedMarketplaces: ['Hotmart Brazil', 'Amazon.com.br Kindle', 'Kobo Brazil'],
    estimatedEffort: 'MEDIUM',
    confidence: 'MEDIUM',
    existingSalesSignal: 'High Hotmart affiliate demand in LatAm education channels',
    status: 'OPPORTUNITY',
  },
  {
    id: 'opp-loc-fr',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    languageCode: 'fr',
    territoryCode: 'FR',
    localeCode: 'fr-FR',
    localeName: 'French (France)',
    priorityScore: 64,
    rsaUnlockPts: 2.2,
    unlockedMarketplaces: ['Fnac / Kobo France', 'Amazon.fr Kindle', 'Apple Books France'],
    estimatedEffort: 'HIGH',
    confidence: 'MEDIUM',
    status: 'OPPORTUNITY',
  },
];
