/**
 * DRAWDOWN OS — AUTONOMOUS EXPERIMENTATION & OPTIMISATION ENGINE
 * Seeded Demo Dataset — Clearly tagged DEMO.
 */

import type {
  Experiment, ExperimentOpportunity, ExperimentLearning, OptimisationCommandStats,
  OptimisationMapCell, OptimisationCoverage, ExperimentBudget, ExperimentCalendarEvent as CalendarEvent,
  MarketplaceExperimentCapability
} from './types';

// ─── COMMAND STATS ────────────────────────────────────────────────────────────

export const DEMO_OPTIMISATION_STATS: OptimisationCommandStats = {
  experimentsRunning: 2,
  awaitingApproval: 3,
  completedThisMonth: 8,
  winners: 5,
  losers: 2,
  inconclusive: 1,
  stoppedByGuardrail: 1,
  estimatedIncrementalRevenueGbp: 12_400,
  estimatedIncrementalContributionGbp: 8_620,
  lossesPreventedGbp: 1_450,
  averageExperimentRoi: 4.8,
  averageTimeToDayDecision: 18.5,
  experimentsPerMonth: 12,
  revenueUnderExperimentationPct: 28.4,
  learningsInLibrary: 14,
  overallLearningConfidence: 'STRONG',
};

// ─── DEMO EXPERIMENTS ─────────────────────────────────────────────────────────

export const DEMO_EXPERIMENTS: Experiment[] = [
  {
    id: 'exp-001',
    name: 'How to Trade Gumroad UK Price Increase (£29 → £34)',
    type: 'PRICING',
    subtype: 'PRICE_INCREASE',
    state: 'ROLLED_OUT',
    health: 'HEALTHY',
    autonomyLevel: 'OPTIMISE',
    hypothesis: {
      id: 'hyp-001',
      experimentId: 'exp-001',
      statement: 'Increasing How to Trade price from £29 to £34 on Gumroad UK will increase net contribution without causing conversion decline >5%.',
      primaryMetric: 'NET_CONTRIBUTION',
      primaryDirection: 'INCREASE',
      affectedEntity: 'Product: How to Trade (DD-HTT-001)',
      baseline: 'Price: £29.00, Conversion: 4.1%, Net Contribution: £2,100/mo',
      proposedChange: 'Set price to £34.00 on Gumroad UK',
      target: 'Net contribution +10%, conversion >= 3.9%',
      secondaryMetrics: ['CONVERSION_RATE', 'UNITS_SOLD', 'AOV'],
      guardrailMetrics: [
        { id: 'g-001', name: 'Refund Rate Floor', metric: 'refund_rate_pct', operator: 'GREATER_THAN', threshold: 5.0, unit: '%', class: 'HARD_STOP', description: 'Stop if refunds exceed 5%', revertOnBreach: true },
        { id: 'g-002', name: 'Conversion Drop Limit', metric: 'conversion_drop_pct', operator: 'GREATER_THAN', threshold: 10.0, unit: '%', class: 'HARD_STOP', description: 'Stop if conversion drops >10%', revertOnBreach: true }
      ],
      minimumDetectableEffect: 5,
      expectedImpactLowGbp: 480,
      expectedImpactHighGbp: 1_200,
      confidence: 'HIGH',
      supportingEvidence: ['Competitor benchmark at £35', 'Price elasticity model signal'],
      linkedObjectiveId: 'obj-001',
      authorType: 'AI',
      authorName: 'Opportunity Miner Engine',
      isDemo: true,
      createdAt: '2026-07-15T09:00:00Z',
    },
    variants: [
      { id: 'var-ctrl', experimentId: 'exp-001', role: 'CONTROL', label: 'Control (£29.00)', description: 'Original price £29.00', changes: [], trafficAllocationPct: 50, isActive: false, isDemo: true },
      { id: 'var-[#34]', experimentId: 'exp-001', role: 'VARIANT_A', label: 'Variant A (£34.00)', description: 'Tested price £34.00', changes: [{ field: 'price_gbp', originalValue: 29, variantValue: 34, changeType: 'PRICE' }], trafficAllocationPct: 50, isActive: true, isDemo: true }
    ],
    guardrails: [
      { id: 'g-001', name: 'Refund Rate Floor', metric: 'refund_rate_pct', operator: 'GREATER_THAN', threshold: 5.0, unit: '%', class: 'HARD_STOP', description: 'Stop if refunds exceed 5%', revertOnBreach: true }
    ],
    primaryMetric: 'NET_CONTRIBUTION',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade',
    marketplaceId: 'mkt-gumroad-uk',
    marketplaceName: 'Gumroad UK',
    territory: 'UK',
    linkedObjectiveId: 'obj-001',
    platformCapability: 'FULL_SPLIT',
    actualStart: '2026-07-16T00:00:00Z',
    actualEnd: '2026-08-01T00:00:00Z',
    minimumDurationDays: 14,
    maximumDurationDays: 30,
    requiredSampleSize: 250,
    currentSample: 312,
    dataSufficiency: 'STRONG',
    priorityScore: 92,
    experimentQualityScore: 95,
    result: {
      id: 'res-001',
      experimentId: 'exp-001',
      outcome: 'WINNER',
      controlMeasurements: { id: 'm-ctrl', experimentId: 'exp-001', variantId: 'var-ctrl', measuredAt: '2026-08-01T00:00:00Z', visitors: 156, orders: 6, grossRevenueGbp: 174, netRevenueGbp: 156, contributionGbp: 140, refunds: 0, refundRatePct: 0, conversionRatePct: 3.84, avgOrderValueGbp: 29.00, isDemo: true },
      variantMeasurements: { id: 'm-var', experimentId: 'exp-001', variantId: 'var-[#34]', measuredAt: '2026-08-01T00:00:00Z', visitors: 156, orders: 7, grossRevenueGbp: 238, netRevenueGbp: 214, contributionGbp: 196, refunds: 0, refundRatePct: 0, conversionRatePct: 4.48, avgOrderValueGbp: 34.00, isDemo: true },
      bayesian: {
        probabilityVariantBetterPct: 94,
        probabilityUpliftExceedsMde: 82,
        expectedUpliftLowPct: 6.2,
        expectedUpliftHighPct: 16.8,
        expectedUpliftMedianPct: 11.4,
        expectedDownsideGbp: 12,
        expectedUpsideGbpMonthly: 420,
        recommendation: 'ROLL_OUT',
        recommendationReason: 'Variant B (£34) demonstrated 94% probability of outperforming control with +11.4% net contribution uplift and 0 guardrail breaches.',
        dataSufficiency: 'STRONG',
      },
      practicalSignificance: { upliftPct: 11.4, annualisedImpactGbp: 1_840, implementationComplexity: 'LOW', rolloutRecommended: true, reason: 'High commercial value (£1,840/yr) with zero operational complexity.' },
      incrementalContributionGbp: 56,
      annualisedValueGbp: 1_840,
      implementationCostGbp: 0,
      roi: 18.4,
      experimentCostGbp: 0,
      humanHoursSpent: 0.5,
      guardRailBreaches: [],
      recommendation: 'ROLL_OUT',
      decisionRationale: 'Strong statistical signal, positive practical significance, low risk.',
      learningGenerated: true,
      evaluatedAt: '2026-08-01T08:00:00Z',
      isDemo: true,
    },
    rollout: {
      id: 'rol-001',
      experimentId: 'exp-001',
      winnerVariantId: 'var-[#34]',
      status: 'COMPLETE',
      phases: [
        { phase: 1, description: 'Gumroad UK full 100% rollout', scope: 'Gumroad UK', status: 'COMPLETE', completedDate: '2026-08-02T00:00:00Z', notes: 'Applied automatically via API.' }
      ],
      postRolloutMonitoringDays: [7, 30, 90],
      postRolloutChecks: [
        { daysMark: 7, expectedContributionGbp: 420, observedContributionGbp: 445, variancePct: 5.9, status: 'ON_TRACK', checkedAt: '2026-08-09T00:00:00Z' }
      ],
      isDemo: true,
      createdAt: '2026-08-02T00:00:00Z',
    },
    createdBy: 'AI',
    createdAt: '2026-07-15T09:00:00Z',
    isDemo: true,
  },
  {
    id: 'exp-002',
    name: 'Etsy US Thumbnail Creative Test (Clean Typography vs Badges)',
    type: 'CREATIVE',
    subtype: 'THUMBNAIL',
    state: 'LOSER',
    health: 'HEALTHY',
    autonomyLevel: 'MANAGE',
    hypothesis: {
      id: 'hyp-002',
      experimentId: 'exp-002',
      statement: 'Adding prominent value badges to Etsy US thumbnail image will increase click-through and overall listing conversion by +8%.',
      primaryMetric: 'CONVERSION_RATE',
      primaryDirection: 'INCREASE',
      affectedEntity: 'Product: How to Trade (DD-HTT-001) / Etsy US',
      baseline: 'Current thumbnail (clean typography), Conversion: 4.31%',
      proposedChange: 'Upload thumbnail variant with 3 yellow guarantee badges',
      target: 'Conversion >= 4.65%',
      secondaryMetrics: ['NET_CONTRIBUTION', 'UNITS_SOLD'],
      guardrailMetrics: [
        { id: 'g-003', name: 'Conversion Floor', metric: 'conversion_drop_pct', operator: 'GREATER_THAN', threshold: 8.0, unit: '%', class: 'HARD_STOP', description: 'Stop if conversion drops >8%', revertOnBreach: true }
      ],
      minimumDetectableEffect: 6,
      expectedImpactLowGbp: 200,
      expectedImpactHighGbp: 650,
      confidence: 'MODERATE',
      supportingEvidence: ['Competitor listing visual audit'],
      linkedObjectiveId: 'obj-001',
      authorType: 'HUMAN',
      authorName: 'Pete Currey',
      isDemo: true,
      createdAt: '2026-07-20T10:00:00Z',
    },
    variants: [
      { id: 'var-thumb-ctrl', experimentId: 'exp-002', role: 'CONTROL', label: 'Control (Clean)', description: 'Minimalist cover style', changes: [], trafficAllocationPct: 50, isActive: true, isDemo: true },
      { id: 'var-thumb-[#1]', experimentId: 'exp-002', role: 'VARIANT_A', label: 'Variant A (Badged)', description: 'Yellow promotional badge overlay', changes: [{ field: 'thumbnail_url', originalValue: 'thumb_v1.png', variantValue: 'thumb_v2_badged.png', changeType: 'CREATIVE' }], trafficAllocationPct: 50, isActive: false, isDemo: true }
    ],
    guardrails: [],
    primaryMetric: 'CONVERSION_RATE',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade',
    marketplaceId: 'mkt-etsy-us',
    marketplaceName: 'Etsy US',
    territory: 'US',
    platformCapability: 'SEQUENTIAL_ONLY',
    actualStart: '2026-07-22T00:00:00Z',
    actualEnd: '2026-08-05T00:00:00Z',
    minimumDurationDays: 14,
    maximumDurationDays: 30,
    requiredSampleSize: 400,
    currentSample: 418,
    dataSufficiency: 'ADEQUATE',
    priorityScore: 68,
    experimentQualityScore: 82,
    result: {
      id: 'res-002',
      experimentId: 'exp-002',
      outcome: 'LOSER',
      controlMeasurements: { id: 'm-ctrl2', experimentId: 'exp-002', variantId: 'var-thumb-ctrl', measuredAt: '2026-08-05T00:00:00Z', visitors: 209, orders: 9, grossRevenueGbp: 261, netRevenueGbp: 235, contributionGbp: 180, refunds: 0, refundRatePct: 0, conversionRatePct: 4.31, avgOrderValueGbp: 29.00, isDemo: true },
      variantMeasurements: { id: 'm-var2', experimentId: 'exp-002', variantId: 'var-thumb-[#1]', measuredAt: '2026-08-05T00:00:00Z', visitors: 209, orders: 7, grossRevenueGbp: 203, netRevenueGbp: 182, contributionGbp: 135, refunds: 0, refundRatePct: 0, conversionRatePct: 3.35, avgOrderValueGbp: 29.00, isDemo: true },
      bayesian: {
        probabilityVariantBetterPct: 6,
        probabilityUpliftExceedsMde: 1,
        expectedUpliftLowPct: -14.2,
        expectedUpliftHighPct: -2.1,
        expectedUpliftMedianPct: -8.2,
        expectedDownsideGbp: 145,
        expectedUpsideGbpMonthly: 0,
        recommendation: 'ROLL_BACK',
        recommendationReason: 'Variant A (Badged) resulted in an 8.2% conversion drop (3.35% vs 4.31% control). Reverted to control.',
        dataSufficiency: 'ADEQUATE',
      },
      practicalSignificance: { upliftPct: -8.2, annualisedImpactGbp: -540, implementationComplexity: 'LOW', rolloutRecommended: false, reason: 'Negative impact on conversion. Cluttered badges reduced trust on Etsy platform.' },
      incrementalContributionGbp: -45,
      annualisedValueGbp: -540,
      implementationCostGbp: 0,
      roi: 0,
      experimentCostGbp: 0,
      humanHoursSpent: 1.2,
      guardRailBreaches: [],
      recommendation: 'ROLL_BACK',
      decisionRationale: 'Statistically significant negative impact. Clean design outperforms aggressive promotional badges on Etsy.',
      learningGenerated: true,
      evaluatedAt: '2026-08-05T09:00:00Z',
      isDemo: true,
    },
    rollbackState: [
      { id: 'rb-001', experimentId: 'exp-002', variantId: 'var-thumb-[#1]', field: 'thumbnail_url', originalValue: 'thumb_v1.png', changedValue: 'thumb_v2_badged.png', changedAt: '2026-07-22T00:00:00Z', affectedEntityType: 'LISTING', affectedEntityId: 'lst-etsy-001', rollbackMethod: 'API_CALL', rolledBackAt: '2026-08-05T09:15:00Z', rolledBackBy: 'Autopilot Engine', isDemo: true }
    ],
    createdBy: 'HUMAN',
    createdAt: '2026-07-20T10:00:00Z',
    isDemo: true,
  },
  {
    id: 'exp-003',
    name: 'Payhip Validation Experiment (How to Trade UK Launch)',
    type: 'DISTRIBUTION',
    subtype: 'MARKETPLACE_LAUNCH',
    state: 'RUNNING',
    health: 'HEALTHY',
    autonomyLevel: 'OPTIMISE',
    hypothesis: {
      id: 'hyp-003',
      experimentId: 'exp-003',
      statement: 'Distributing How to Trade on Payhip UK will yield £200+ monthly net contribution within 30 days at 5% platform fee.',
      primaryMetric: 'NET_CONTRIBUTION',
      primaryDirection: 'INCREASE',
      affectedEntity: 'Marketplace: Payhip UK / How to Trade',
      baseline: 'No Payhip listing',
      proposedChange: 'Create Payhip UK listing at £29.00',
      target: 'Contribution >= £200 in 30 days',
      secondaryMetrics: ['UNITS_SOLD', 'CONVERSION_RATE'],
      guardrailMetrics: [
        { id: 'g-004', name: 'Refund Threshold', metric: 'refund_rate_pct', operator: 'GREATER_THAN', threshold: 6.0, unit: '%', class: 'HARD_STOP', description: 'Stop if refunds exceed 6%', revertOnBreach: true }
      ],
      minimumDetectableEffect: 10,
      expectedImpactLowGbp: 180,
      expectedImpactHighGbp: 520,
      confidence: 'MODERATE',
      supportingEvidence: ['Marketplace Radar 91% fit score'],
      linkedObjectiveId: 'obj-001',
      authorType: 'AI',
      authorName: 'Marketplace Radar Engine',
      isDemo: true,
      createdAt: '2026-08-05T00:00:00Z',
    },
    variants: [
      { id: 'var-payhip-main', experimentId: 'exp-003', role: 'VARIANT_A', label: 'Payhip £29 Listing', description: 'Standard listing at £29', changes: [], trafficAllocationPct: 100, isActive: true, isDemo: true }
    ],
    guardrails: [],
    primaryMetric: 'NET_CONTRIBUTION',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade',
    marketplaceId: 'mkt-payhip-uk',
    marketplaceName: 'Payhip UK',
    territory: 'UK',
    platformCapability: 'MANUAL_EXECUTION',
    actualStart: '2026-08-05T00:00:00Z',
    minimumDurationDays: 30,
    maximumDurationDays: 60,
    requiredSampleSize: 100,
    currentSample: 38,
    dataSufficiency: 'INSUFFICIENT',
    estimatedDaysToDecision: 18,
    priorityScore: 84,
    experimentQualityScore: 88,
    aiCommentary: 'Day 7 of 30. Sample currently 38 visitors / 3 sales (£87 gross). 0 refunds. On track for £300+ 30-day run rate.',
    createdBy: 'AI',
    createdAt: '2026-08-05T00:00:00Z',
    isDemo: true,
  },
  {
    id: 'exp-004',
    name: 'How to Trade German Copy Guardrail Breach (Gumroad DE)',
    type: 'PRODUCT_POSITIONING',
    subtype: 'TRANSLATED_DESCRIPTION',
    state: 'STOPPED',
    health: 'STOPPED',
    autonomyLevel: 'MANAGE',
    hypothesis: {
      id: 'hyp-004',
      experimentId: 'exp-004',
      statement: 'Localised German landing copy emphasizing rapid beginner results will increase DACH conversion rate by +25%.',
      primaryMetric: 'CONVERSION_RATE',
      primaryDirection: 'INCREASE',
      affectedEntity: 'Product: How to Trade (German) / Gumroad DE',
      baseline: 'Standard English translation copy',
      proposedChange: 'Revised high-promise German copy',
      target: 'Conversion >= 3.5%',
      secondaryMetrics: ['GROSS_REVENUE'],
      guardrailMetrics: [
        { id: 'g-005', name: 'Refund Threshold Breach', metric: 'refund_rate_pct', operator: 'GREATER_THAN', threshold: 7.0, unit: '%', class: 'HARD_STOP', description: 'Hard stop if refund rate >7%', revertOnBreach: true }
      ],
      minimumDetectableEffect: 10,
      expectedImpactLowGbp: 300,
      expectedImpactHighGbp: 900,
      confidence: 'LOW',
      supportingEvidence: ['DACH market survey'],
      linkedObjectiveId: 'obj-001',
      authorType: 'HUMAN',
      authorName: 'Localisation Team',
      isDemo: true,
      createdAt: '2026-08-01T00:00:00Z',
    },
    variants: [
      { id: 'var-de-ctrl', experimentId: 'exp-004', role: 'CONTROL', label: 'Control (Standard German)', description: 'Literal translation', changes: [], trafficAllocationPct: 50, isActive: false, isDemo: true },
      { id: 'var-de-aggressive', experimentId: 'exp-004', role: 'VARIANT_A', label: 'Variant A (Aggressive Copy)', description: 'High-promise outcome copy', changes: [{ field: 'description', originalValue: 'Standard German text', variantValue: 'Aggressive German copy', changeType: 'COPY' }], trafficAllocationPct: 50, isActive: false, isDemo: true }
    ],
    guardrails: [
      { id: 'g-005', name: 'Refund Threshold Breach', metric: 'refund_rate_pct', operator: 'GREATER_THAN', threshold: 7.0, unit: '%', class: 'HARD_STOP', description: 'Hard stop if refund rate >7%', revertOnBreach: true }
    ],
    primaryMetric: 'CONVERSION_RATE',
    productSku: 'DD-HTT-001-DE',
    productName: 'How to Trade (German)',
    marketplaceId: 'mkt-gumroad-de',
    marketplaceName: 'Gumroad DE',
    territory: 'DE',
    platformCapability: 'FULL_SPLIT',
    actualStart: '2026-08-02T00:00:00Z',
    actualEnd: '2026-08-08T00:00:00Z',
    minimumDurationDays: 14,
    maximumDurationDays: 30,
    requiredSampleSize: 200,
    currentSample: 145,
    dataSufficiency: 'ADEQUATE',
    priorityScore: 71,
    experimentQualityScore: 65,
    result: {
      id: 'res-004',
      experimentId: 'exp-004',
      outcome: 'STOPPED_GUARDRAIL',
      controlMeasurements: { id: 'mc-de', experimentId: 'exp-004', variantId: 'var-de-ctrl', measuredAt: '2026-08-08T00:00:00Z', visitors: 70, orders: 2, grossRevenueGbp: 58, netRevenueGbp: 52, contributionGbp: 38, refunds: 0, refundRatePct: 0, conversionRatePct: 2.85, avgOrderValueGbp: 29.00, isDemo: true },
      variantMeasurements: { id: 'mv-de', experimentId: 'exp-004', variantId: 'var-de-aggressive', measuredAt: '2026-08-08T00:00:00Z', visitors: 75, orders: 4, grossRevenueGbp: 116, netRevenueGbp: 104, contributionGbp: 42, refunds: 2, refundRatePct: 8.2, conversionRatePct: 5.33, avgOrderValueGbp: 29.00, isDemo: true },
      bayesian: {
        probabilityVariantBetterPct: 78,
        probabilityUpliftExceedsMde: 60,
        expectedUpliftLowPct: 2.0,
        expectedUpliftHighPct: 24.0,
        expectedUpliftMedianPct: 12.0,
        expectedDownsideGbp: 380,
        expectedUpsideGbpMonthly: 120,
        recommendation: 'ROLL_BACK',
        recommendationReason: 'HARD STOP: Refund rate reached 8.2% (threshold: 7.0%). High-promise copy created expectation mismatch among German readers.',
        dataSufficiency: 'ADEQUATE',
      },
      practicalSignificance: { upliftPct: 12.0, annualisedImpactGbp: -450, implementationComplexity: 'MEDIUM', rolloutRecommended: false, reason: 'Conversion increased but refund rate exceeded safety limit. Negative net commercial value due to refunds and account risk.' },
      incrementalContributionGbp: -120,
      annualisedValueGbp: -450,
      implementationCostGbp: 0,
      roi: 0,
      experimentCostGbp: 0,
      humanHoursSpent: 2.0,
      guardRailBreaches: [
        { definitionId: 'g-005', name: 'Refund Threshold Breach', metric: 'refund_rate_pct', threshold: 7.0, currentValue: 8.2, unit: '%', class: 'HARD_STOP', isBreached: true, breachedAt: '2026-08-08T08:14:00Z' }
      ],
      recommendation: 'ROLL_BACK',
      decisionRationale: 'Automatic emergency stop executed due to hard guardrail breach. Reverted copy immediately.',
      learningGenerated: true,
      evaluatedAt: '2026-08-08T08:15:00Z',
      isDemo: true,
    },
    rollbackState: [
      { id: 'rb-de-001', experimentId: 'exp-004', variantId: 'var-de-aggressive', field: 'description', originalValue: 'Standard German text', changedValue: 'Aggressive German copy', changedAt: '2026-08-02T00:00:00Z', affectedEntityType: 'LISTING', affectedEntityId: 'lst-gumroad-de-001', rollbackMethod: 'AUTOMATIC', rolledBackAt: '2026-08-08T08:16:00Z', rolledBackBy: 'Guardrail Engine', isDemo: true }
    ],
    createdBy: 'HUMAN',
    createdAt: '2026-08-01T00:00:00Z',
    isDemo: true,
  },
  {
    id: 'exp-005',
    name: 'HTT + Workbook Bundle Pricing on Etsy US',
    type: 'MERCHANDISING',
    subtype: 'BUNDLE',
    state: 'INCONCLUSIVE',
    health: 'WATCH',
    autonomyLevel: 'DESIGN',
    hypothesis: {
      id: 'hyp-005',
      experimentId: 'exp-005',
      statement: 'Offering a bundle of How to Trade + Companion Workbook at £39.00 (20% off combined price of £48) will increase Average Order Value by +30%.',
      primaryMetric: 'AOV',
      primaryDirection: 'INCREASE',
      affectedEntity: 'Product: How to Trade + Workbook Bundle / Etsy US',
      baseline: 'Single HTT purchase AOV: £29.00',
      proposedChange: 'Create bundle listing at £39.00',
      target: 'AOV >= £36.00',
      secondaryMetrics: ['NET_CONTRIBUTION', 'BUNDLE_ATTACH_RATE'],
      guardrailMetrics: [],
      minimumDetectableEffect: 15,
      expectedImpactLowGbp: 350,
      expectedImpactHighGbp: 850,
      confidence: 'MODERATE',
      supportingEvidence: ['Customer survey interest in workbooks'],
      linkedObjectiveId: 'obj-001',
      authorType: 'AI',
      authorName: 'Opportunity Miner Engine',
      isDemo: true,
      createdAt: '2026-07-10T00:00:00Z',
    },
    variants: [
      { id: 'var-bundle-no', experimentId: 'exp-005', role: 'CONTROL', label: 'Control (No Bundle)', description: 'Separate listings only', changes: [], trafficAllocationPct: 50, isActive: false, isDemo: true },
      { id: 'var-bundle-yes', experimentId: 'exp-005', role: 'VARIANT_A', label: 'Variant A (£39 Bundle)', description: 'Bundle option enabled', changes: [{ field: 'bundle_listing', originalValue: 'none', variantValue: 'bundle_htt_wkb_39', changeType: 'CONFIGURATION' }], trafficAllocationPct: 50, isActive: false, isDemo: true }
    ],
    guardrails: [],
    primaryMetric: 'AOV',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade',
    marketplaceId: 'mkt-etsy-us',
    marketplaceName: 'Etsy US',
    territory: 'US',
    platformCapability: 'SEQUENTIAL_ONLY',
    actualStart: '2026-07-12T00:00:00Z',
    actualEnd: '2026-07-26T00:00:00Z',
    minimumDurationDays: 14,
    maximumDurationDays: 30,
    requiredSampleSize: 500,
    currentSample: 182,
    dataSufficiency: 'INSUFFICIENT',
    priorityScore: 65,
    experimentQualityScore: 78,
    result: {
      id: 'res-005',
      experimentId: 'exp-005',
      outcome: 'INCONCLUSIVE',
      controlMeasurements: { id: 'mc-bun', experimentId: 'exp-005', variantId: 'var-bundle-no', measuredAt: '2026-07-26T00:00:00Z', visitors: 91, orders: 4, grossRevenueGbp: 116, netRevenueGbp: 104, contributionGbp: 80, refunds: 0, refundRatePct: 0, conversionRatePct: 4.39, avgOrderValueGbp: 29.00, isDemo: true },
      variantMeasurements: { id: 'mv-bun', experimentId: 'exp-005', variantId: 'var-bundle-yes', measuredAt: '2026-07-26T00:00:00Z', visitors: 91, orders: 3, grossRevenueGbp: 117, netRevenueGbp: 105, contributionGbp: 82, refunds: 0, refundRatePct: 0, conversionRatePct: 3.29, avgOrderValueGbp: 39.00, isDemo: true },
      bayesian: {
        probabilityVariantBetterPct: 52,
        probabilityUpliftExceedsMde: 30,
        expectedUpliftLowPct: -15.0,
        expectedUpliftHighPct: +18.0,
        expectedUpliftMedianPct: +1.5,
        expectedDownsideGbp: 40,
        expectedUpsideGbpMonthly: 120,
        recommendation: 'INCONCLUSIVE',
        recommendationReason: 'INCONCLUSIVE: Sample size (182 visitors) insufficient to separate signal from noise (need 500+). Probability variant is better is 52% (effectively coin flip).',
        dataSufficiency: 'INSUFFICIENT',
        estimatedDaysToDecision: 22,
      },
      practicalSignificance: { upliftPct: 1.5, annualisedImpactGbp: 120, implementationComplexity: 'LOW', rolloutRecommended: false, reason: 'Sample insufficient. Recommend re-testing when Etsy traffic volume increases or combining with email campaign.' },
      incrementalContributionGbp: 2,
      annualisedValueGbp: 120,
      implementationCostGbp: 0,
      roi: 1.2,
      experimentCostGbp: 0,
      humanHoursSpent: 0.8,
      guardRailBreaches: [],
      recommendation: 'RETEST',
      decisionRationale: 'Do not make rollout decision on noise. Retest with higher traffic volume.',
      learningGenerated: false,
      evaluatedAt: '2026-07-26T09:00:00Z',
      isDemo: true,
    },
    createdBy: 'AI',
    createdAt: '2026-07-10T00:00:00Z',
    isDemo: true,
  },
];

// ─── DEMO LEARNINGS ───────────────────────────────────────────────────────────

export const DEMO_LEARNINGS: ExperimentLearning[] = [
  {
    id: 'lrn-001',
    type: 'PRICING',
    scope: 'CATEGORY',
    title: 'Beginner Trading PDFs Show Low Price Elasticity Between £24–£34',
    statement: 'Customers purchasing entry-to-intermediate trading educational PDFs display minimal conversion sensitivity to price increases from £24 up to £34, yielding higher net contribution.',
    implication: 'Future beginner educational products should be priced at £29–£34 at launch rather than starting at £19–£24.',
    experimentIds: ['exp-001'],
    productSkus: ['DD-HTT-001'],
    marketplaceIds: ['mkt-gumroad-uk', 'mkt-etsy-us'],
    territories: ['UK', 'US'],
    totalCustomersInEvidence: 482,
    confidence: 'STRONG',
    evidenceCount: 3,
    isContradicted: false,
    createdAt: '2026-08-01T00:00:00Z',
    lastValidatedAt: '2026-08-01T00:00:00Z',
    currentRelevance: 'HIGH',
    isDemo: true,
  },
  {
    id: 'lrn-002',
    type: 'POSITIONING',
    scope: 'TERRITORY',
    title: 'German Readers Value Accuracy Over High-Outcome Promises',
    statement: 'Aggressive outcome-focused marketing copy in German-language listings causes expectation mismatch and increases refund rate to >8%, whereas sober factual copy maintains refund rates <3%.',
    implication: 'Localised DACH copy must use restrained, educational, compliance-focused language rather than high-promise promotional copy.',
    experimentIds: ['exp-004'],
    productSkus: ['DD-HTT-001-DE'],
    marketplaceIds: ['mkt-gumroad-de'],
    territories: ['DE', 'AT', 'CH'],
    totalCustomersInEvidence: 145,
    confidence: 'MODERATE',
    evidenceCount: 2,
    isContradicted: false,
    createdAt: '2026-08-08T00:00:00Z',
    lastValidatedAt: '2026-08-08T00:00:00Z',
    currentRelevance: 'HIGH',
    isDemo: true,
  },
  {
    id: 'lrn-003',
    type: 'CREATIVE',
    scope: 'MARKETPLACE',
    title: 'Etsy Buyers Prefer Minimalist Covers to Promotional Badges',
    statement: 'Adding bright promotional guarantee badges to Etsy thumbnails reduced conversion by -8.2%, as Etsy buyers perceive heavy sales badges as low-quality or spammy.',
    implication: 'Maintain clean, typographic, editorial-grade thumbnails for all Etsy listings.',
    experimentIds: ['exp-002'],
    productSkus: ['DD-HTT-001'],
    marketplaceIds: ['mkt-etsy-us'],
    territories: ['US'],
    totalCustomersInEvidence: 418,
    confidence: 'STRONG',
    evidenceCount: 2,
    isContradicted: false,
    createdAt: '2026-08-05T00:00:00Z',
    lastValidatedAt: '2026-08-05T00:00:00Z',
    currentRelevance: 'HIGH',
    isDemo: true,
  },
];

// ─── DEMO OPPORTUNITIES ───────────────────────────────────────────────────────

export const DEMO_OPTIMISATION_OPPORTUNITIES: ExperimentOpportunity[] = [
  {
    id: 'op-001',
    source: 'PRICE_NEVER_TESTED',
    experimentType: 'PRICING',
    experimentSubtype: 'PRICE_INCREASE',
    title: 'Test £34 → £39 Price Increase on Etsy US',
    knowledgeGap: 'We do not know if Etsy US customers will tolerate a £39 price point for How to Trade.',
    hypothesis: 'Raising HTT from £34 to £39 on Etsy US will yield +£480–£720 monthly contribution assuming <6% conversion drop.',
    expectedValueLowGbp: 480,
    expectedValueHighGbp: 720,
    learningValueScope: 'PRODUCT',
    priorityScore: 88,
    effort: 'LOW',
    risk: 'LOW',
    reversibility: 'EASY',
    relatedProductSku: 'DD-HTT-001',
    relatedMarketplaceId: 'mkt-etsy-us',
    territory: 'US',
    linkedObjectiveId: 'obj-001',
    isDemo: true,
    detectedAt: '2026-08-11T00:00:00Z',
  },
  {
    id: 'op-002',
    source: 'LOW_BUNDLE_ATTACH',
    experimentType: 'MERCHANDISING',
    experimentSubtype: 'BUNDLE',
    title: 'Test HTT + Quiet Edge Trading Mindset Bundle',
    knowledgeGap: 'We have never tested combining HTT with The Quiet Edge as a high-margin bundle.',
    hypothesis: 'Bundling HTT + TQE for £45 (saving £13) will increase AOV by +£11 on direct/Payhip traffic.',
    expectedValueLowGbp: 350,
    expectedValueHighGbp: 800,
    learningValueScope: 'PORTFOLIO',
    priorityScore: 81,
    effort: 'MEDIUM',
    risk: 'LOW',
    reversibility: 'EASY',
    relatedProductSku: 'DD-HTT-001',
    linkedObjectiveId: 'obj-001',
    isDemo: true,
    detectedAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'op-003',
    source: 'HIGH_TRAFFIC_LOW_CONVERSION',
    experimentType: 'CONVERSION',
    experimentSubtype: 'LANDING_PAGE',
    title: 'Test Table of Contents Preview on Payhip UK',
    knowledgeGap: 'Does showing a detailed 3-page PDF table of contents preview increase checkout conversion?',
    hypothesis: 'Adding a 3-page sample preview image to Payhip listing will increase conversion from 2.8% to 3.8%.',
    expectedValueLowGbp: 220,
    expectedValueHighGbp: 450,
    learningValueScope: 'CATEGORY',
    priorityScore: 76,
    effort: 'LOW',
    risk: 'LOW',
    reversibility: 'EASY',
    relatedProductSku: 'DD-HTT-001',
    relatedMarketplaceId: 'mkt-payhip-uk',
    territory: 'UK',
    isDemo: true,
    detectedAt: '2026-08-12T00:00:00Z',
  },
];

// ─── OPTIMISATION MAP COVERAGE DATA ──────────────────────────────────────────

export const DEMO_OPTIMISATION_MAP: OptimisationMapCell[] = [
  { productSku: 'DD-HTT-001', productName: 'How to Trade', marketplaceId: 'mkt-gumroad-uk', marketplaceName: 'Gumroad UK', dimension: 'PRICING', status: 'STRONG_EVIDENCE', revenueAtRiskGbp: 2_100, lastTestedAt: '2026-08-01', experimentId: 'exp-001' },
  { productSku: 'DD-HTT-001', productName: 'How to Trade', marketplaceId: 'mkt-etsy-us', marketplaceName: 'Etsy US', dimension: 'CREATIVE', status: 'STRONG_EVIDENCE', revenueAtRiskGbp: 4_420, lastTestedAt: '2026-08-05', experimentId: 'exp-002' },
  { productSku: 'DD-HTT-001', productName: 'How to Trade', marketplaceId: 'mkt-etsy-us', marketplaceName: 'Etsy US', dimension: 'PRICING', status: 'UNTESTED', revenueAtRiskGbp: 4_420 },
  { productSku: 'DD-HTT-001', productName: 'How to Trade', marketplaceId: 'mkt-payhip-uk', marketplaceName: 'Payhip UK', dimension: 'DISTRIBUTION', status: 'ACTIVE', revenueAtRiskGbp: 0, lastTestedAt: '2026-08-05', experimentId: 'exp-003' },
  { productSku: 'DD-HTT-001-DE', productName: 'How to Trade (DE)', marketplaceId: 'mkt-gumroad-de', marketplaceName: 'Gumroad DE', dimension: 'POSITIONING', status: 'UNDERPERFORMING', revenueAtRiskGbp: 890, lastTestedAt: '2026-08-08', experimentId: 'exp-004' },
  { productSku: 'DD-TQE-001', productName: 'The Quiet Edge', marketplaceId: 'mkt-gumroad-us', marketplaceName: 'Gumroad US', dimension: 'PRICING', status: 'UNTESTED', revenueAtRiskGbp: 1_220 },
];

export const DEMO_OPTIMISATION_COVERAGE: OptimisationCoverage[] = [
  { dimension: 'PRICING', coveragePct: 68, revenueTestedGbp: 6_520, totalRevenueGbp: 9_590, experimentsCompleted: 4 },
  { dimension: 'CREATIVE', coveragePct: 46, revenueTestedGbp: 4_420, totalRevenueGbp: 9_590, experimentsCompleted: 2 },
  { dimension: 'POSITIONING', coveragePct: 22, revenueTestedGbp: 2_110, totalRevenueGbp: 9_590, experimentsCompleted: 2 },
  { dimension: 'DISTRIBUTION', coveragePct: 35, revenueTestedGbp: 3_350, totalRevenueGbp: 9_590, experimentsCompleted: 3 },
  { dimension: 'BUNDLES', coveragePct: 14, revenueTestedGbp: 1_340, totalRevenueGbp: 9_590, experimentsCompleted: 1 },
  { dimension: 'LOCALISATION', coveragePct: 8, revenueTestedGbp: 890, totalRevenueGbp: 9_590, experimentsCompleted: 1 },
];

// ─── DEMO BUDGET ──────────────────────────────────────────────────────────────

export const DEMO_EXPERIMENT_BUDGET: ExperimentBudget = {
  id: 'bgt-2026-08',
  period: '2026-08',
  linkedObjectiveId: 'obj-001',
  totalDownsideBudgetGbp: 500,
  usedDownsideGbp: 142,
  remainingDownsideGbp: 358,
  experimentsCount: 3,
  isDemo: true,
};

// ─── PLATFORM CAPABILITIES ───────────────────────────────────────────────────

export const DEMO_PLATFORM_CAPABILITIES: MarketplaceExperimentCapability[] = [
  { marketplaceId: 'mkt-gumroad', marketplaceName: 'Gumroad', priceTest: 'FULL_SPLIT', thumbnailTest: true, descriptionTest: true, tagsTest: false, trafficSplit: true, checkoutTest: 'LIMITED', notes: 'Full A/B support for price and description.' },
  { marketplaceId: 'mkt-etsy', marketplaceName: 'Etsy', priceTest: 'SEQUENTIAL_ONLY', thumbnailTest: true, descriptionTest: true, tagsTest: true, trafficSplit: false, checkoutTest: 'NOT_SUPPORTED', notes: 'Etsy does not support native split testing. Use sequential week-by-week tests.' },
  { marketplaceId: 'mkt-payhip', marketplaceName: 'Payhip', priceTest: 'FULL_SPLIT', thumbnailTest: true, descriptionTest: true, tagsTest: false, trafficSplit: true, checkoutTest: 'NOT_SUPPORTED', notes: 'Instant price and content updates supported.' },
  { marketplaceId: 'mkt-direct', marketplaceName: 'Direct Drawdown Storefront', priceTest: 'FULL_SPLIT', thumbnailTest: true, descriptionTest: true, tagsTest: true, trafficSplit: true, checkoutTest: 'FULL', notes: 'Highest control environment. Full split, checkout, and bundle testing.' },
];
