/**
 * DRAWDOWN OS — AUTONOMOUS LISTING & MERCHANDISING ENGINE
 * Demo Data — Test Product: HOW TO TRADE (DD-HTT-001)
 * Merchandised across Amazon, Etsy, Whop, Hotmart and Direct Drawdown.
 */

import type {
  MarketplaceListing, MarketplaceListingVersion, MerchandisingStrategy,
  MarketplacePositioning, ListingCopyVariant, SearchTerm, GallerySequenceItem,
  ListingPrice, MerchandisingExperiment, ListingDriftEvent, MerchandisingRecommendation,
  BrandVocabularyItem, MerchandisingAutopilotPolicy, MarketplaceMerchandisingProfile,
} from './types';

// ─── MARKETPLACE PROFILES ─────────────────────────────────────────────────────

export const MARKETPLACE_PROFILES: Record<string, MarketplaceMerchandisingProfile> = {
  'ch-amazon-kdp': {
    id: 'mp-amazon',
    marketplaceId: 'ch-amazon-kdp',
    marketplaceName: 'Amazon KDP / Kindle Store',
    primaryBuyerBehaviours: ['Title discovery', 'Book category browsing', 'Author credibility', 'Cover presentation', 'Description', 'Customer reviews', 'Look Inside sample', 'Price'],
    titleLimit: 200,
    subtitleLimit: 200,
    shortDescriptionLimit: 300,
    longDescriptionLimit: 4000,
    htmlSupported: true,
    bulletsSupported: true,
    maxBullets: 5,
    tagsSupported: false,
    maxTags: 7, // 7 search keywords
    maxGalleryImages: 1, // KDP cover
    requiresRiskWarning: false,
    requiresDisclaimer: true,
    sampleTypesSupported: ['Look Inside sample', 'First chapter PDF'],
    automationEligible: false,
  },
  'ch-etsy': {
    id: 'mp-etsy',
    marketplaceId: 'ch-etsy',
    marketplaceName: 'Etsy Digital Marketplace',
    primaryBuyerBehaviours: ['Visual search', 'Downloadable usefulness', 'Gallery story', 'Product bundle presentation', 'Printable/workbook appeal', 'Tags'],
    titleLimit: 140,
    shortDescriptionLimit: 200,
    longDescriptionLimit: 2000,
    htmlSupported: false,
    bulletsSupported: true,
    maxBullets: 8,
    tagsSupported: true,
    maxTags: 13,
    maxGalleryImages: 10,
    requiresRiskWarning: true,
    requiresDisclaimer: true,
    sampleTypesSupported: ['Toolkit preview PDF', 'Sample chapter'],
    automationEligible: true,
  },
  'ch-whop': {
    id: 'mp-[#whop]',
    marketplaceId: 'ch-whop',
    marketplaceName: 'Whop Creator Commerce',
    primaryBuyerBehaviours: ['Digital-product utility', 'Creator/product trust', 'Product benefits list', 'Ecosystem/community positioning'],
    titleLimit: 100,
    shortDescriptionLimit: 250,
    longDescriptionLimit: 5000,
    htmlSupported: true,
    bulletsSupported: true,
    maxBullets: 6,
    tagsSupported: true,
    maxTags: 5,
    maxGalleryImages: 5,
    requiresRiskWarning: true,
    requiresDisclaimer: true,
    sampleTypesSupported: ['Free checklist sample', 'Chapter 1 PDF'],
    automationEligible: true,
  },
  'ch-hotmart': {
    id: 'mp-hotmart',
    marketplaceId: 'ch-hotmart',
    marketplaceName: 'Hotmart Education Marketplace',
    primaryBuyerBehaviours: ['Educational product positioning', 'Affiliate distribution', 'Offer structure', 'Sales page presentation'],
    titleLimit: 100,
    shortDescriptionLimit: 200,
    longDescriptionLimit: 2000,
    htmlSupported: false,
    bulletsSupported: true,
    maxBullets: 5,
    tagsSupported: true,
    maxTags: 10,
    maxGalleryImages: 4,
    requiresRiskWarning: true,
    requiresDisclaimer: true,
    sampleTypesSupported: ['Programme overview', 'Sample PDF'],
    automationEligible: true,
  },
  'ch-direct': {
    id: 'mp-direct',
    marketplaceId: 'ch-direct',
    marketplaceName: 'Direct Drawdown Store (drawdown.os)',
    primaryBuyerBehaviours: ['Brand authority', 'Cross-sell', 'Bundling', 'Customer ownership', 'Product ladder', 'Lifetime relationship'],
    titleLimit: 255,
    subtitleLimit: 255,
    shortDescriptionLimit: 500,
    longDescriptionLimit: 10000,
    htmlSupported: true,
    bulletsSupported: true,
    maxBullets: 12,
    tagsSupported: true,
    maxTags: 20,
    maxGalleryImages: 12,
    requiresRiskWarning: true,
    requiresDisclaimer: true,
    sampleTypesSupported: ['First 3 chapters', 'Full toolkit preview', 'Interactive sample'],
    automationEligible: true,
  },
};

// ─── CANONICAL LISTINGS ───────────────────────────────────────────────────────

export const DEMO_LISTINGS: MarketplaceListing[] = [
  {
    id: 'lst-amz-htt-001',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    marketplaceId: 'ch-amazon-kdp',
    marketplaceName: 'Amazon KDP',
    territoryId: 'GLOBAL',
    languageId: 'en',
    externalListingId: 'B0D98X7Y1A',
    externalUrl: 'https://amazon.com/dp/B0D98X7Y1A',
    listingVersion: 1,
    status: 'LIVE',
    approvalStatus: 'APPROVED',
    complianceStatus: 'PASS',
    publicationStatus: 'LIVE',
    merchandisingStrategyId: 'strat-htt-amz',
    activeExperimentId: 'exp-amz-001',
    currentPriceId: 'pr-htt-amz',
    discoverabilityScore: 84,
    listingQualityScore: 92,
    performanceState: 'HEALTHY',
    netRevenueGbp: 1420.50,
    conversionRatePct: 4.8,
    refundRatePct: 1.2,
    isDrifted: false,
    lastSyncedAt: '2024-08-12T14:30:00Z',
    lastVerifiedAt: '2024-08-12T14:30:00Z',
    createdAt: '2024-04-01T00:00:00Z',
    updatedAt: '2024-08-12T14:30:00Z',
  },
  {
    id: 'lst-etsy-htt-001',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    marketplaceId: 'ch-etsy',
    marketplaceName: 'Etsy Digital',
    territoryId: 'GLOBAL',
    languageId: 'en',
    externalListingId: 'ETSY-18273645',
    externalUrl: 'https://etsy.com/listing/ETSY-18273645',
    listingVersion: 2,
    status: 'STALE',
    approvalStatus: 'APPROVED',
    complianceStatus: 'PASS',
    publicationStatus: 'LIVE',
    merchandisingStrategyId: 'strat-htt-etsy',
    currentPriceId: 'pr-htt-etsy',
    discoverabilityScore: 68,
    listingQualityScore: 74,
    performanceState: 'UNDERPERFORMING',
    netRevenueGbp: 640.20,
    conversionRatePct: 2.1,
    refundRatePct: 0.8,
    isDrifted: true,
    driftSeverity: 'MEDIUM',
    lastSyncedAt: '2024-07-20T10:00:00Z',
    lastVerifiedAt: '2024-08-12T09:15:00Z',
    createdAt: '2024-04-05T00:00:00Z',
    updatedAt: '2024-08-12T09:15:00Z',
  },
  {
    id: 'lst-whop-htt-001',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    marketplaceId: 'ch-whop',
    marketplaceName: 'Whop Commerce',
    territoryId: 'GLOBAL',
    languageId: 'en',
    externalListingId: 'prod_whop_9921',
    externalUrl: 'https://whop.com/drawdown/how-to-trade',
    listingVersion: 1,
    status: 'LIVE',
    approvalStatus: 'APPROVED',
    complianceStatus: 'PASS',
    publicationStatus: 'LIVE',
    merchandisingStrategyId: 'strat-htt-whop',
    currentPriceId: 'pr-htt-whop',
    discoverabilityScore: 78,
    listingQualityScore: 88,
    performanceState: 'HIGH_PERFORMING',
    netRevenueGbp: 2150.00,
    conversionRatePct: 6.4,
    refundRatePct: 1.5,
    isDrifted: false,
    lastSyncedAt: '2024-08-11T18:00:00Z',
    lastVerifiedAt: '2024-08-11T18:00:00Z',
    createdAt: '2024-04-10T00:00:00Z',
    updatedAt: '2024-08-11T18:00:00Z',
  },
  {
    id: 'lst-hotmart-htt-001',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    marketplaceId: 'ch-hotmart',
    marketplaceName: 'Hotmart',
    territoryId: 'GLOBAL',
    languageId: 'en',
    externalListingId: 'HOT-994827',
    externalUrl: 'https://hotmart.com/product/how-to-trade',
    listingVersion: 1,
    status: 'OPTIMISING',
    approvalStatus: 'APPROVED',
    complianceStatus: 'PASS',
    publicationStatus: 'LIVE',
    merchandisingStrategyId: 'strat-htt-hotmart',
    currentPriceId: 'pr-htt-hotmart',
    discoverabilityScore: 62,
    listingQualityScore: 71,
    performanceState: 'LEARNING',
    netRevenueGbp: 320.00,
    conversionRatePct: 3.0,
    refundRatePct: 2.1,
    isDrifted: false,
    lastSyncedAt: '2024-08-10T12:00:00Z',
    lastVerifiedAt: '2024-08-10T12:00:00Z',
    createdAt: '2024-05-01T00:00:00Z',
    updatedAt: '2024-08-10T12:00:00Z',
  },
  {
    id: 'lst-direct-htt-001',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade (Complete Manual)',
    marketplaceId: 'ch-direct',
    marketplaceName: 'Direct Drawdown Store',
    territoryId: 'GLOBAL',
    languageId: 'en',
    externalListingId: 'DD-STORE-001',
    externalUrl: 'https://drawdown.os/products/how-to-trade',
    listingVersion: 3,
    status: 'LIVE',
    approvalStatus: 'APPROVED',
    complianceStatus: 'PASS',
    publicationStatus: 'LIVE',
    merchandisingStrategyId: 'strat-htt-direct',
    activeExperimentId: 'exp-direct-002',
    currentPriceId: 'pr-htt-direct',
    discoverabilityScore: 95,
    listingQualityScore: 98,
    performanceState: 'HIGH_PERFORMING',
    netRevenueGbp: 4890.00,
    conversionRatePct: 8.2,
    refundRatePct: 0.6,
    isDrifted: false,
    lastSyncedAt: '2024-08-12T16:00:00Z',
    lastVerifiedAt: '2024-08-12T16:00:00Z',
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2024-08-12T16:00:00Z',
  },
];

// ─── STRATEGIES & POSITIONING ─────────────────────────────────────────────────

export const MERCHANDISING_STRATEGIES: Record<string, MerchandisingStrategy> = {
  'strat-htt-amz': {
    id: 'strat-htt-amz',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-amazon-kdp',
    primaryAudience: 'Self-directed beginner trader seeking authoritative, book-formatted education',
    secondaryAudience: 'Intermediate trader looking for risk management structure',
    primaryCustomerJob: 'LEARN + IMPLEMENT',
    primaryCommercialAngle: 'Comprehensive 19-chapter master manual on financial trading without signals or hype',
    primaryValueProp: 'Structured, evidence-based trading manual emphasizing risk management over quick profits',
    supportingValueProps: [
      '19 structured chapters covering foundation to execution',
      'Dedicated risk control & position sizing formulas',
      'No signals, no shortcuts — focus on process & longevity',
    ],
    differentiators: ['Includes actual calculation tables and step-by-step risk management rules', 'Written from institutional risk principles'],
    primaryCta: 'Read sample and order Kindle edition',
    tone: 'Authoritative, calm, educational, objective',
    prohibitedClaims: ['Become profitable', 'Earn £X per day', 'Guaranteed returns', 'Beat the market'],
    riskDisclosures: ['Trading involves risk of capital loss.', 'Past performance does not guarantee future results.'],
    createdAt: '2024-04-01T00:00:00Z',
    updatedAt: '2024-04-01T00:00:00Z',
  },
  'strat-htt-etsy': {
    id: 'strat-htt-etsy',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-etsy',
    primaryAudience: 'Beginner trader seeking structured downloadable education & printable toolkits',
    primaryCustomerJob: 'LEARN + IMPLEMENT',
    primaryCommercialAngle: 'Complete printable trading manual + 90-day framework and risk calculation worksheets',
    primaryValueProp: 'All-in-one downloadable PDF trading manual with printable worksheets and risk tables',
    supportingValueProps: [
      'Instant PDF download suitable for iPad annotation or printing',
      'Includes printable 90-day execution framework & worksheets',
      'Position sizing tables & risk management checklists included',
    ],
    differentiators: ['Clean visual aesthetic with printable worksheets', 'Complete manual + toolkit in one download'],
    primaryCta: 'Instant download — add to cart',
    tone: 'Practical, structured, encouraging, visual',
    prohibitedClaims: ['Passive income guaranteed', 'Trading signals included', 'Easy money'],
    riskDisclosures: ['Educational material only. Not financial advice. Trading carries financial risk.'],
    createdAt: '2024-04-05T00:00:00Z',
    updatedAt: '2024-04-05T00:00:00Z',
  },
  'strat-htt-whop': {
    id: 'strat-htt-whop',
    productId: 'pub-dd-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-whop',
    primaryAudience: 'Digital-first trader looking for structured digital utility and execution framework',
    primaryCustomerJob: 'EXECUTE + CONTROL RISK',
    primaryCommercialAngle: 'Digital trading manual & risk management engine for modern digital traders',
    primaryValueProp: 'Instant digital access to Drawdown OS flagship trading manual & execution toolkit',
    supportingValueProps: [
      'Instant access on mobile & web via Whop portal',
      'Complete 19-chapter curriculum with interactive checklists',
      'Direct integration into Drawdown educational ecosystem',
    ],
    differentiators: ['Digital utility focus — non-guru educational framework'],
    primaryCta: 'Unlock instant access',
    tone: 'Sleek, direct, utility-focused, modern',
    prohibitedClaims: ['Signal group access', 'Guaranteed win rate'],
    riskDisclosures: ['Trading involves risk of loss. For educational purposes only.'],
    createdAt: '2024-04-10T00:00:00Z',
    updatedAt: '2024-04-10T00:00:00Z',
  },
};

// ─── COPY VARIANTS & PROVENANCE ───────────────────────────────────────────────

export const COPY_VARIANTS: ListingCopyVariant[] = [
  {
    id: 'copy-amz-title',
    listingId: 'lst-amz-htt-001',
    fieldName: 'title',
    variantText: 'How to Trade: The Complete Master Manual on Risk, Strategy and Execution',
    characterCount: 78,
    characterLimit: 200,
    isCondensed: false,
    contentFidelity: 'SOURCE_DERIVED',
    sourceChunkIds: ['ce-001'],
    approvedClaimIds: ['claim-001'],
    status: 'LIVE',
  },
  {
    id: 'copy-amz-short',
    listingId: 'lst-amz-htt-001',
    fieldName: 'short_desc',
    variantText: 'A structured 19-chapter manual detailing institutional risk management, position sizing, and trade execution. Built without signals, shortcuts, or hype.',
    characterCount: 161,
    characterLimit: 300,
    isCondensed: true,
    contentFidelity: 'SOURCE_DERIVED',
    sourceChunkIds: ['ce-001', 'ce-009'],
    approvedClaimIds: ['claim-001', 'claim-002'],
    status: 'LIVE',
  },
  {
    id: 'copy-etsy-title',
    listingId: 'lst-etsy-htt-001',
    fieldName: 'title',
    variantText: 'Complete Trading Manual PDF | 19 Chapters, Worksheets & Position Sizing Toolkit',
    characterCount: 88,
    characterLimit: 140,
    isCondensed: true,
    contentFidelity: 'SOURCE_DERIVED',
    sourceChunkIds: ['ce-001', 'ce-012'],
    approvedClaimIds: ['claim-001', 'claim-003'],
    status: 'LIVE',
  },
];

// ─── SEARCH INTENTS & KEYWORDS ────────────────────────────────────────────────

export const SEARCH_TERMS: SearchTerm[] = [
  {
    id: 'st-001',
    term: 'beginner trading guide',
    marketplaceId: 'ch-amazon-kdp',
    territoryId: 'GLOBAL',
    languageId: 'en',
    productSku: 'DD-HTT-001',
    intentCategory: 'INFORMATIONAL',
    sourceType: 'RESEARCHED',
    volumeEstimate: 14500,
    competitionLevel: 'HIGH',
    performanceCtr: 0.052,
    isApproved: true,
    isBlocked: false,
    confidence: 'HIGH',
    lastCheckedAt: '2024-08-12T00:00:00Z',
  },
  {
    id: 'st-002',
    term: 'risk management trading workbook',
    marketplaceId: 'ch-etsy',
    territoryId: 'GLOBAL',
    languageId: 'en',
    productSku: 'DD-HTT-001',
    intentCategory: 'TRANSACTIONAL',
    sourceType: 'OBSERVED',
    volumeEstimate: 3800,
    competitionLevel: 'MEDIUM',
    performanceCtr: 0.084,
    isApproved: true,
    isBlocked: false,
    confidence: 'HIGH',
    lastCheckedAt: '2024-08-12T00:00:00Z',
  },
  {
    id: 'st-003',
    term: 'position sizing trading guide',
    marketplaceId: 'ch-whop',
    territoryId: 'GLOBAL',
    languageId: 'en',
    productSku: 'DD-HTT-001',
    intentCategory: 'PROBLEM_SPECIFIC',
    sourceType: 'OBSERVED',
    volumeEstimate: 2100,
    competitionLevel: 'LOW',
    performanceCtr: 0.112,
    isApproved: true,
    isBlocked: false,
    confidence: 'HIGH',
    lastCheckedAt: '2024-08-12T00:00:00Z',
  },
];

// ─── GALLERY SEQUENCES ────────────────────────────────────────────────────────

export const GALLERY_SEQUENCES: Record<string, GallerySequenceItem[]> = {
  'lst-etsy-htt-001': [
    { id: 'gal-1', listingId: 'lst-etsy-htt-001', position: 1, purpose: 'COVER', assetId: 'ast-cov-001', assetUrl: '/assets/covers/htt-etsy-cover.jpg', label: 'Primary Master Cover', overlayMessage: 'Complete Trading Manual PDF', status: 'READY' },
    { id: 'gal-2', listingId: 'lst-etsy-htt-001', position: 2, purpose: 'WHAT_IS_INCLUDED', assetId: 'ast-inc-001', assetUrl: '/assets/gallery/htt-included.jpg', label: 'What Is Included', overlayMessage: '19 Chapters + 90-Day Toolkit', status: 'READY' },
    { id: 'gal-3', listingId: 'lst-etsy-htt-001', position: 3, purpose: 'INSIDE_PAGES', assetId: 'ast-ins-001', assetUrl: '/assets/gallery/htt-inside.jpg', label: 'Inside Pages Spread', overlayMessage: 'Clean, structured PDF formatting', status: 'READY' },
    { id: 'gal-4', listingId: 'lst-etsy-htt-001', position: 4, purpose: 'PROGRAMME', assetId: 'ast-prg-001', assetUrl: '/assets/gallery/htt-programme.jpg', label: '90-Day Execution Framework', overlayMessage: 'Sequential learning system', status: 'STALE' },
    { id: 'gal-5', listingId: 'lst-etsy-htt-001', position: 5, purpose: 'WORKSHEETS', assetId: 'ast-wrk-001', assetUrl: '/assets/gallery/htt-worksheets.jpg', label: 'Printable Worksheets', overlayMessage: 'Position sizing & trade log sheets', status: 'READY' },
    { id: 'gal-6', listingId: 'lst-etsy-htt-001', position: 6, purpose: 'RISK_WARNING', assetId: 'ast-rsk-001', assetUrl: '/assets/gallery/htt-risk.jpg', label: 'Risk-First Education', overlayMessage: 'Zero signals. Zero hype.', status: 'READY' },
  ],
};

// ─── PRICING ECONOMICS ────────────────────────────────────────────────────────

export const LISTING_PRICES: Record<string, ListingPrice> = {
  'pr-htt-amz': {
    id: 'pr-htt-amz',
    listingId: 'lst-amz-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-amazon-kdp',
    basePriceGbp: 24.99,
    marketplacePriceGbp: 19.99,
    minPriceFloorGbp: 14.99,
    autopilotFloorGbp: 17.99,
    estimatedPlatformFeePct: 30.00,
    estimatedNetProceedsGbp: 13.99,
    netMarginPct: 70.0,
    priceParityStatus: 'OK',
  },
  'pr-htt-etsy': {
    id: 'pr-htt-etsy',
    listingId: 'lst-etsy-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-etsy',
    basePriceGbp: 24.99,
    marketplacePriceGbp: 21.99,
    minPriceFloorGbp: 14.99,
    autopilotFloorGbp: 17.99,
    estimatedPlatformFeePct: 9.50,
    estimatedNetProceedsGbp: 19.90,
    netMarginPct: 90.5,
    priceParityStatus: 'OK',
  },
  'pr-htt-whop': {
    id: 'pr-htt-whop',
    listingId: 'lst-whop-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-whop',
    basePriceGbp: 24.99,
    marketplacePriceGbp: 24.99,
    minPriceFloorGbp: 14.99,
    autopilotFloorGbp: 19.99,
    estimatedPlatformFeePct: 3.00,
    estimatedNetProceedsGbp: 24.24,
    netMarginPct: 97.0,
    priceParityStatus: 'OK',
  },
  'pr-htt-direct': {
    id: 'pr-htt-direct',
    listingId: 'lst-direct-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-direct',
    basePriceGbp: 24.99,
    marketplacePriceGbp: 24.99,
    minPriceFloorGbp: 14.99,
    autopilotFloorGbp: 19.99,
    estimatedPlatformFeePct: 2.50,
    estimatedNetProceedsGbp: 24.36,
    netMarginPct: 97.5,
    priceParityStatus: 'OK',
  },
};

// ─── MERCHANDISING EXPERIMENTS ────────────────────────────────────────────────

export const MERCHANDISING_EXPERIMENTS: MerchandisingExperiment[] = [
  {
    id: 'exp-amz-001',
    listingId: 'lst-amz-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade',
    marketplaceId: 'ch-amazon-kdp',
    marketplaceName: 'Amazon KDP',
    experimentName: 'Subtitle Risk Emphasis Test',
    hypothesis: 'Emphasizing risk management in the subtitle rather than strategy will increase product-page conversion without raising refunds.',
    testType: 'A_B',
    variableTested: 'SUBTITLE',
    controlVariant: { label: 'Control: Strategy & Execution focus', details: 'A Master Manual on Strategy and Execution' },
    testVariant: { label: 'Variant B: Institutional Risk focus', details: 'The Master Manual on Institutional Risk Control' },
    successMetric: 'NET_REVENUE',
    guardrailMetrics: ['REFUND_RATE', 'MARGIN', 'COMPLIANCE'],
    startAt: '2024-08-01T00:00:00Z',
    minDurationDays: 14,
    status: 'RUNNING',
    confidenceLevel: 'MODERATE_CONFIDENCE',
    createdAt: '2024-08-01T00:00:00Z',
  },
  {
    id: 'exp-direct-002',
    listingId: 'lst-direct-htt-001',
    productSku: 'DD-HTT-001',
    productName: 'How to Trade',
    marketplaceId: 'ch-direct',
    marketplaceName: 'Direct Drawdown Store',
    experimentName: 'Workbook Bundle vs Standalone Price Test',
    hypothesis: 'Offering a manual + workbook bundle option on product page increases average order value and net revenue by 15%.',
    testType: 'MARKETPLACE_NATIVE',
    variableTested: 'OFFER',
    controlVariant: { label: 'Control: Standalone manual (£24.99)', details: 'Single manual purchase' },
    testVariant: { label: 'Variant B: Manual + Workbook Bundle (£34.99)', details: 'Includes printable workbook' },
    successMetric: 'NET_REVENUE',
    guardrailMetrics: ['REFUND_RATE', 'MARGIN'],
    startAt: '2024-07-25T00:00:00Z',
    minDurationDays: 14,
    status: 'COMPLETED',
    confidenceLevel: 'HIGH_CONFIDENCE',
    winnerVariant: 'VARIANT',
    decisionReason: 'Variant B generated +22.4% higher net revenue per visitor with 0.4% lower refund rate.',
    createdAt: '2024-07-25T00:00:00Z',
  },
];

// ─── LISTING DRIFT EVENTS ──────────────────────────────────────────────────────

export const DRIFT_EVENTS: ListingDriftEvent[] = [
  {
    id: 'drf-001',
    listingId: 'lst-etsy-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-etsy',
    fieldDrifted: 'gallery_sequence',
    expectedValue: 'Gallery Image 4 = ast-prg-002 (V1.1 Updated Programme)',
    liveValue: 'Gallery Image 4 = ast-prg-001 (V1.0 Stale Programme)',
    severity: 'MEDIUM',
    detectedAt: '2024-08-12T09:15:00Z',
  },
];

// ─── MERCHANDISING RECOMMENDATIONS ────────────────────────────────────────────

export const RECOMMENDATIONS: MerchandisingRecommendation[] = [
  {
    id: 'rec-001',
    listingId: 'lst-etsy-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-etsy',
    title: 'ADD TOOLKIT PREVIEW TO ETSY GALLERY',
    actionType: 'ASSET_UPDATE',
    diagnosis: 'Listing has strong search views but gallery image 4 is stale and does not clearly show included worksheets.',
    proposedAction: 'Deploy updated V1.1 Gallery Image 4 showing printable 90-day worksheets preview.',
    estimatedImpactPts: 4.5,
    effortLevel: 'LOW',
    confidence: 'HIGH',
    requiresHumanApproval: false, // Autopilot eligible
    status: 'PENDING',
    createdAt: '2024-08-12T10:00:00Z',
  },
  {
    id: 'rec-002',
    listingId: 'lst-hotmart-htt-001',
    productSku: 'DD-HTT-001',
    marketplaceId: 'ch-hotmart',
    title: 'CREATE APPROVED AFFILIATE CREATIVE PACK',
    actionType: 'AFFILIATE_PACK',
    diagnosis: 'Hotmart listing conversion is learning phase; affiliates lack approved compliance copy.',
    proposedAction: 'Generate and lock approved affiliate creative pack with zero-signal compliance disclosures.',
    estimatedImpactPts: 6.2,
    effortLevel: 'MEDIUM',
    confidence: 'HIGH',
    requiresHumanApproval: true,
    status: 'PENDING',
    createdAt: '2024-08-12T11:30:00Z',
  },
];

// ─── BRAND VOCABULARY ─────────────────────────────────────────────────────────

export const BRAND_VOCABULARY: BrandVocabularyItem[] = [
  { id: 'bv-1', term: 'trading signals', classification: 'PROHIBITED', reason: 'Drawdown does not sell or endorse trading signals.', suggestedAlternative: 'structured educational framework' },
  { id: 'bv-2', term: 'guaranteed returns', classification: 'PROHIBITED', reason: 'No financial return promises allowed.', suggestedAlternative: 'risk management guidelines' },
  { id: 'bv-3', term: 'passive income', classification: 'PROHIBITED', reason: 'Misleading financial claim.', suggestedAlternative: 'systematic execution methodology' },
  { id: 'bv-4', term: 'risk control', classification: 'PREFERRED', reason: 'Aligns with core Drawdown philosophy.' },
  { id: 'bv-5', term: 'position sizing', classification: 'APPROVED', reason: 'Core technical discipline.' },
];

// ─── AUTOPILOT POLICY ─────────────────────────────────────────────────────────

export const DEFAULT_AUTOPILOT_POLICY: MerchandisingAutopilotPolicy = {
  autoRepairDrift: true,
  autoDeployApprovedWinner: false,
  autoUpdateKeywords: true,
  autoUpdateApprovedAssets: false,
  autoSyncPrice: true,
  autoEndPromotions: true,
  maxConcurrentExperiments: 3,
  maxPriceVariancePct: 10.0,
  minTrafficForExperiment: 500,
};
